### ISSUE TITLE
[Bug] FinishUrl ignored when using shopware 6 store-api

### ISSUE THREAD

**Issue by meeshoogendoorn** [buckaroo-it/Shopware-6-plugin#11]
Hello,

I am using Shopware-pwa and shopware 6 for our ecommerce platform. We are using buckaroo as the PSP for our project. When we test a payment we will always get redirected to our Shopware 6 instance while the payment gets initialized by our pwa.

pwa.com-> we initiate payment -> shopware.com/store-api/handlePayment -> shopware6.com

I asked the Developer team of the Shopware PWA team how this was possible and this is what they say.

`
Hi guys, the payment plugin must handle finishUrl and errorUrl that are provided within handlePayment method after the order is placed. finishUrl is an only thing that can tell the backend on what page a customer should be redirected to, after the payment succeeds. 
It looks like the handlePaymentByOrder method (part of PaymentService) is being invoked internally in the plugin with some other finishUrl provided, so the correct pwa url is ignored during handlePayment call 
`

is it possible to fix this so that the finishUrl and errorUrl in the `handlePaymentByOrder` method will listen to the values provided by the store-api so that we can use your plugin with our PWA.

**Comment by Buckaroo-Rens** [comment]
Hi @meeshoogendoorn we need to do some research on this topic. Will come back to you with a final answer a.s.a.p.

**Comment by meeshoogendoorn** [comment]
@Buckaroo-Rens Thanks, i will wait for your reaction. If i can do something let me know or if u need some extra information.

Here is the simple but effective documentation about creating aan paymentOrder with Shopware 6 store api from shopware-pwa docs.

https://shopware-pwa-docs.vuestorefront.io/landing/concepts/payment.html#intro

**Comment by meeshoogendoorn** [comment]
I have created a pull request so u can checkout the problem. See this link #12

**Comment by saranchuk-hys** [comment]
Thank you @meeshoogendoorn , for you pull request
