### ISSUE TITLE
[BUG] Client sided Creditcards payment

### ISSUE THREAD

**Issue by meeshoogendoorn** [buckaroo-it/Shopware-6-plugin#13]
When using creditcard clientsided payment i always get an error.  The error is thrown when using shopware 6 but also when using the Shopware PWA. 

```php
#data: array:23 [▼
    "Key" => "TRANSAXCTION_KEY"
    "Status" => array:3 [▼
      "Code" => array:2 [▼
        "Code" => 491
        "Description" => "Validation failure"
      ]
      "SubCode" => null
      "DateTime" => "2021-09-02T11:22:55"
    ]
    "RequiredAction" => null
    "Services" => null
    "CustomParameters" => null
    "AdditionalParameters" => array:1 [▼
      "AdditionalParameter" => array:3 [▶]
    ]
    "RequestErrors" => array:5 [▼
      "ChannelErrors" => []
      "ServiceErrors" => array:1 [▼
        0 => array:3 [▼
          "Name" => "creditcards"
          "Error" => "ServiceUnknown"
          "ErrorMessage" => "'creditcards' is not a valid service name."
        ]
      ]
      "ActionErrors" => array:1 [▼
        0 => array:4 [▼
          "Service" => null
          "Name" => null
          "Error" => "ActionPrimaryMissing"
          "ErrorMessage" => "No primary action specified. Please specify 1 primary action."
        ]
      ]
      "ParameterErrors" => []
      "CustomParameterErrors" => []
    ]
    "Invoice" => "10014"
    "ServiceCode" => null
    "IsTest" => true
    "Currency" => "EUR"
    "AmountDebit" => 497.94
    "TransactionType" => null
    "MutationType" => 0
    "RelatedTransactions" => null
    "ConsumerMessage" => null
    "Order" => "10014"
    "IssuingCountry" => null
    "StartRecurrent" => false
    "Recurring" => false
    "CustomerName" => null
    "PayerHash" => null
    "PaymentKey" => null
  ]
  #curlInfo: array:37 [▼
    "url" => "https://testcheckout.buckaroo.nl/json/Transaction"
    "content_type" => "application/json"
    "http_code" => 200
    "header_size" => 441
    "request_size" => 478
    "filetime" => -1
    "ssl_verify_result" => 0
    "redirect_count" => 0
    "total_time" => 0.14999
    "namelookup_time" => 0.001644
    "connect_time" => 0.012173
    "pretransfer_time" => 0.042892
    "size_upload" => 1269.0
    "size_download" => 1153.0
    "speed_download" => 7738.0
    "speed_upload" => 8516.0
    "download_content_length" => 1153.0
    "upload_content_length" => 1269.0
    "starttransfer_time" => 0.055043
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "SOME_IP"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "192.168.10.110"
    "local_port" => 58928
    "http_version" => 2
    "protocol" => 2
    "ssl_verifyresult" => 0
    "scheme" => "HTTPS"
    "appconnect_time_us" => 42837
    "connect_time_us" => 12173
    "namelookup_time_us" => 1644
    "pretransfer_time_us" => 42892
    "redirect_time_us" => 0
    "starttransfer_time_us" => 55043
    "total_time_us" => 149990
  ]
  #headers: array:10 [▼
    "server" => array:1 [▶]
    "date" => array:1 [▶]
    "content-type" => array:1 [▶]
    "content-length" => array:1 [▶]
    "cache-control" => array:1 [▶]
    "pragma" => array:1 [▶]
    "expires" => array:1 [▶]
    "authorization" => array:1 [▶]
    "x-robots-tag" => array:1 [▶]
    "strict-transport-security" => array:1 [▶]
  ]
```

This is a test payment here. I can't fid why it is not working. Do u guys have any idea what the problem could be?

**Comment by vladislav-padalka-hys** [comment]
Good afternoon @meeshoogendoorn !

We've re-tested our recent plugin's version (1.2.2) with Shopware 6.4.3.1 how it goes for client side credit cards and there is no issue with orders. 
Can you please specify some additional information (e.g.: Buckaroo plugin version, Shopware version, browser version, etc) ? So we can try exactly your case.
Or if it's comfortable for you then please contact our support team for exact environment location, so we can try to identify the issue there directly.

Thanks in advance !

**Comment by vladislav-padalka-hys** [comment]
Good morning @meeshoogendoorn !

Does this issue still to be actual for you ? 
Did you contact somebody at our support ? 
We definitely need more info to try solve your case

**Comment by meeshoogendoorn** [comment]
@vladislav-padalka-hys Hey sorry for the late reaction. I had contact with @Buckaroo-Rens by LinkedIn. I was really busy with some side jobs so that's why this reaction is this late. I will check our store settings and post it all here so u can look at it.

**Comment by meeshoogendoorn** [comment]
Well, I have to tell u something just tested some payment local and it is working now. I just experienced the most stupid error in my live, Until now 😨  

I was encrypting the card data with your encryptedCard library in the pwa but because of some formatter he was adding a whitespace to the expirationMonth and expirationYear. I couldn't see this because i encrypted the card data straight away and send it to SW6. So the data i was sending in the encryptor was

```js 
BuckarooClientSideEncryption.V001.encryptCardData(
          "123456789", 
          "06 ",
          "2022 ", 
         "000",
          "MY NAME"
)
```

Your ClientSideEncryptionLibrary will encrypt this with the whitespace o i replaced the whitespaces with a replaceAll and now its working like a charm. 

Sorry guys for bothering u, Hope u can still have a little laugh about my stupid error 😆 
Thanks for your time 👍
