### ISSUE TITLE
[Question] Payment State

### ISSUE THREAD

**Issue by meeshoogendoorn** [buckaroo-it/Shopware-6-plugin#14]
I have an issue where when i place an test order and i select it to be cancelled or success, the shopware 6 payment status doesn't get updated. Is there something like an extra setting i need to enable to get this functionality working?

Below u see my settings for the plugin:
<img width="756" alt="Screenshot 2021-09-14 at 14 51 56" src="https://user-images.githubusercontent.com/55089200/133280094-40ad4c00-cc8e-4f5b-b955-c4ddca033190.png">
<img width="1095" alt="Screenshot 2021-09-14 at 14 52 09" src="https://user-images.githubusercontent.com/55089200/133280105-6ff4940a-e489-4c16-853a-c013742cbcf7.png">
<img width="1095" alt="Screenshot 2021-09-14 at 14 52 27" src="https://user-images.githubusercontent.com/55089200/133280115-04b0a311-bee2-4ab9-8125-7b7a7c0f97d7.png">

<img width="1362" alt="Screenshot 2021-09-14 at 16 48 40" src="https://user-images.githubusercontent.com/55089200/133280301-3658fee6-9735-4ba7-9b23-6bc33447ef46.png">
As u can see in the last image all my orders have payment status open but u i have paid them.

**Comment by saranchuk-hys** [comment]
Hello @meeshoogendoorn , Thank you for your question
For correct change order status, push url should be public and available from anywhere

If this is not issue, could you please contact https://support.buckaroo.nl/contact and provide your server credentials, and we will check

**Comment by meeshoogendoorn** [comment]
@saranchuk-hys I will check this out end of the week. We have basic auth and ip auth on our dev server at the moment. I will run a test at the end of the week.

**Comment by meeshoogendoorn** [comment]
@saranchuk-hys I checked this out this morning and everything works fine now. We had basic auth on our shopware 6 instance so buckaroo couldn't push to this url.

**Comment by saranchuk-hys** [comment]
@rickschippers sure, thank you

**Comment by saranchuk-hys** [comment]
@meeshoogendoorn sure, thank you !
