### ISSUE TITLE
Incorrect signature on partial payments

### ISSUE THREAD

**Issue by rickschippers** [buckaroo-it/Shopware-6-plugin#15]
We have a few orders with partial payments: gift-cards + ideal or creditcard, that do not complete correctly.

An example is this order:

![screenshot-2021-09-28_10 23 29](https://user-images.githubusercontent.com/8250644/135051149-101bf3c5-7136-489e-9f1b-0f695f6e5196.png)

Partly successfully paid with gift-card (20 euro). then another successful gift-card (15 euro). Those are pushed to shopware and handled correctly.

Then two failed gift-card payments of (5.40 euro). An invalid pin was used for the gift-card twice. These got pushed to shopware successfully. The plugin then sets the order status to cancelled.

Then the last part - an ideal payment (5.40) for the remaining part, was paid succesfully. This gets pushed to shopware. But it isn't handled correctly.  Shopware gets the data, logs is in the buckaroo log, then just this line:

`[2021-09-18T09:12:03.447678+00:00] buckaroo_payment.INFO: Buckaroo\Shopware6\Storefront\Controller\PushController::pushBuckaroo|5| [] []`

Which means the message has an invalid signature:

```php
if (!$this->checkoutHelper->validateSignature()) {
            $this->logger->info(__METHOD__ . "|5|");
            return $this->json(['status' => false, 'message' => $this->trans('buckaroo.messages.signatureIncorrect')]);
}
```

So this last push does not get registered/parsed successfully in shopware, and so the order is not re-opened en completed, but it stays on cancelled. And in shopware we are missing the data that the order has been paid successfully.

This seems to happen with partial payment orders, that have failed parts in them.

I can provide you with order / transaction examples if needed. I do not want to post this data on github.

**Comment by rickschippers** [comment]
Looking at the data, this order also has a "+" in  the `brq_SERVICE_ideal_consumerName` and `brq_customer_name`, so this may influence the urldecode part in the signature calculation. I tried a few things with the signature calculation for testing, but I couldn't get the same signature that was posted.

**Comment by saranchuk-hys** [comment]
Hello @rickschippers 
Thank you for issue. 
Bug fixed and will be included to next release

**Comment by rickschippers** [comment]
@saranchuk-hys, I tested with the changes you made. The signature changes (as expected). But it still calculates a different signature than the one that got posted.

**Comment by rickschippers** [comment]
I think there's also still bug with lowercase/uppercase keys. The `decodePushValue` method expects lowercase `$brq_key`'s. But in reality it gets mixed case keys, because of a bug in the `buckarooArraySortMethod`

```    
protected function buckarooArraySort($arrayToUse)
    {
        $arrayToSort   = [];
        $originalArray = [];

        foreach ($arrayToUse as $key => $value) {
            $arrayToSort[strtolower($key)]   = $value;
            $originalArray[strtolower($key)] = $key;
        }

        ksort($arrayToSort);

        $sortableArray = [];

        foreach ($arrayToSort as $key => $value) {
            $key                 = $originalArray[$key];
            $sortableArray[$key] = $value;
        }

        return $sortableArray;
    }
```

In the last foreach it's using the $originalArray[$key] as value for $key. And this is still mixed case. $originalArray has the keys in lowercase, but the values as mixed_cased key names:

```
Array
(
    [add_orderid] => ADD_orderId
    [add_ordertransactionid] => ADD_orderTransactionId
    [add_sw-context-token] => ADD_sw-context-token
    [brq_amount] => brq_amount
    [brq_currency] => brq_currency
    [brq_customer_name] => brq_customer_name
    [brq_description] => brq_description
    [brq_invoicenumber] => brq_invoicenumber
    [brq_mutationtype] => brq_mutationtype
    [brq_payer_hash] => brq_payer_hash
    [brq_payment] => brq_payment
    [brq_relatedtransaction_partialpayment] => brq_relatedtransaction_partialpayment
    [brq_service_ideal_consumerbic] => brq_SERVICE_ideal_consumerBIC
    [brq_service_ideal_consumeriban] => brq_SERVICE_ideal_consumerIBAN
    [brq_service_ideal_consumerissuer] => brq_SERVICE_ideal_consumerIssuer
    [brq_service_ideal_consumername] => brq_SERVICE_ideal_consumerName
    [brq_service_ideal_transactionid] => brq_SERVICE_ideal_transactionId
    [brq_statuscode] => brq_statuscode
    [brq_statuscode_detail] => brq_statuscode_detail
    [brq_statusmessage] => brq_statusmessage
    [brq_test] => brq_test
    [brq_timestamp] => brq_timestamp
    [brq_transaction_method] => brq_transaction_method
    [brq_transaction_type] => brq_transaction_type
    [brq_transactions] => brq_transactions
    [brq_websitekey] => brq_websitekey
    [cust_mailadres] => CUST_mailadres
)
```

But after fixing this, the signature changes, but it's still not correct.

**Comment by rickschippers** [comment]
@saranchuk-hys I tried that, but that doesn't help.
Can I send you the posted data somehow, so you can check with the data we had pushed.

**Comment by rickschippers** [comment]
After our e-mail conversation I realized I was testing with the incorrect secret key. 
The first two commits: 334e39c and 90f79f5, actually fixed the issue. The culprit was the + sign in the customer / consumer name.

**Comment by saranchuk-hys** [comment]
Thank you @rickschippers  for your issue
