### ISSUE TITLE
Partial payments - order gets incorrectly cancelled

### ISSUE THREAD

**Issue by rickschippers** [buckaroo-it/Shopware-6-plugin#16]
With partial payments, a push gets send for each paid part. When a part fails, for whatever reason, the order state is set to cancelled on that push. When a push for a successful payment part is done after that, the order is reopened.  This works when the pushes all get send in the correct order. 

But recently we had an order, that was fully paid in parts (giftcard + ideal). All succesful payments parts got pushed. But 8 seconds after the last successful push, another push with status 490 was sent.  This last push, caused the the order in shopware to be transitioned to cancelled, even though it was fully paid. In turn this prevents the rest of our order process to be initiated. 

![screenshot-2021-09-29_17 14 35](https://user-images.githubusercontent.com/8250644/135417259-e95dbd9c-8728-402c-b166-3dc0b2092510.png)

![screenshot-2021-09-30_10 36 38](https://user-images.githubusercontent.com/8250644/135418021-c78e3997-11cc-407e-bd98-8c245abdfa85.png)

I think the core issue is that a cancelled/failed payment part should probably not cancel the order in the first place since the payment is likely still in progress. 

But definitely the order should not be cancelled when it's been fully paid.

**Comment by saranchuk-hys** [comment]
Hello @rickschippers . Thank you for your issue.
Fix for this was done, and will be included to next release
