### ISSUE TITLE
Tag for version 1.1.3

### ISSUE THREAD

**Issue by samzijlmans** [buckaroo-it/Shopware-6-plugin#2]
The commit b90499c0b30fb5b63acad861b28d440bc2968f60 has updated the composer.json version to 1.1.3, but there is no tag created yet for this version. The latest tag is 1.1.1

Could you create a tag for version 1.1.3? Thanks in advance!

**Comment by saranchuk-hys** [comment]
Thank you @samzijlmans for you issue.
Tag 1.1.3 was skipped, but you can use https://github.com/buckaroo-it/Shopware-6-plugin/releases/tag/v1.1.4
