### ISSUE TITLE
last_used_creditcard has not been set for a new Customer

### ISSUE THREAD

**Issue by peter-bztrs** [buckaroo-it/Shopware-6-plugin#3]
https://github.com/buckaroo-it/Shopware-6-plugin/blob/9fe3867255641b13094b135a8968744a48530b7f/src/Subscribers/CheckoutConfirmTemplateSubscriber.php#L181

When an customer creates a new account, the value 'last_used_creditcard' is not available and generates an error.

![Schermafbeelding 2021-03-09 om 14 27 01](https://user-images.githubusercontent.com/36953693/110478359-8f4cb580-80e4-11eb-9253-0da22d2b7d97.png)

**Comment by saranchuk-hys** [comment]
Hello @peter-bztrs Thank you for your issue. It`s fixed and will include to next release
