### ISSUE TITLE
[critical] Edit order - impossible

### ISSUE THREAD

**Issue by robbertdesmit** [buckaroo-it/Shopware-6-plugin#5]
when installing the plugin the EDIT order button in the admin Order View is not there anymore

buckaroo-payment/extension/sw-order/index.js

computed: {
        isEditable() {
            return !this.isBuckarooPayment || this.$route.name !== 'buckaroo.payment.detail';
        },

**Comment by saranchuk-hys** [comment]
Hello @robbertdesmit , thank you for your issue. 
Bug was fixed, and will be included to the next release.
