### ISSUE TITLE
Partial payments with a cancelled part

### ISSUE THREAD

**Issue by rickschippers** [buckaroo-it/Shopware-6-plugin#6]
When a partial payment has one part that is cancelled the order other in shopware will be cancelled and remain cancelled. Even when other succeful part complete the entire payment.

What happens is when you have a failed part - for example when someone enters an incorrect pin on a giftcard - a push is sent to shopware with a 690 status. This causes and order state change to cancelled.

Then when another payment part has been succesful a new push is sent to shopware with status 190. This is supposed to reopen the order and handle the payment. However the check to see if the order should be reopened breaks. This causes the order to remain cancelled. The rest of the handling fails because you will get illegal state transitions, since the order is still cancelled instead of reopened.

The issue is in the PushController at line 140 - the part that should reopen the order:

```
if ($this->checkoutHelper->isOrderState(['cancelled'], $brqOrderId, $context)) {
  $this->logger->info(__METHOD__ . "|35|");
  $this->checkoutHelper->changeOrderStatus($brqOrderId, $context, 'reopen');
}
```

The order state is being checked to see if the order has the state `cancelled`. This check fails, since it is being checked against:
`StateMachineTransitionActions::ACTION_CANCEL` which is `cancel`, not `cancelled`.

The check is in the `CheckoutHelper->getOrderTransactionStatesNameFromAction`

**Comment by saranchuk-hys** [comment]
Hello @rickschippers 
Thank you for you pull request

**Comment by rickschippers** [comment]
Another side effect of this issue is, that this check will return true if the order state is open. Since the `getOrderTransactionStatesNameFromAction` will return `return OrderTransactionStates::STATE_OPEN;` if it doesn't find a match.

`if ($this->checkoutHelper->isOrderState(['cancelled'], $brqOrderId, $context)) {`
