### ISSUE TITLE
Partial payment - transition issue

### ISSUE THREAD

**Issue by rickschippers** [buckaroo-it/Shopware-6-plugin#9]
This commit https://github.com/buckaroo-it/Shopware-6-plugin/commit/799ec8ed458f6866300aba84d7fbde67caaea2fb introduced a side effect. That cause an exception when receiving succesful partial payment pushes:

`[2021-08-08T14:00:25.904393+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "paidPartially" of class "Shopware\Core\Checkout\Order\Aggregate\OrderTransaction\OrderTransactionStateHandler". Did you mean to call "payPartially"?" at /var/www/vhosts/shopware/releases/20210806125400/vendor/buckaroo/shopware6/src/Helpers/CheckoutHelper.php line 247 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"paidPartially\" of class \"Shopware\\Core\\Checkout\\Order\\Aggregate\\OrderTransaction\\OrderTransactionStateHandler\".\nDid you mean to call \"payPartially\"? at /var/www/vhosts/shopware/releases/20210806125400/vendor/buckaroo/shopware6/src/Helpers/CheckoutHelper.php:247)"} []`

**Comment by saranchuk-hys** [comment]
Thank you @rickschippers for your fix
